### PR TITLE
add bitcoind integration tests and general refactor

### PR DESCRIPTION
**Pull request by maraoz**
See https://github.com/bitpay/bitcore/blob/master/CONTRIBUTING.md#g7---standard-methods

### CODE REVIEW

**Comment by yemel** [comment]
LGTM, @maraoz could you check why the coverage decreased?

**Comment by braydonf** [comment]
LGTM

**Comment by maraoz** [comment]
will review to prevent test coverage decrease, and update to v0.10.x

**Comment by maraoz** [comment]
updated and ready for review :)

**Comment by braydonf** [comment]
I think it would be better to have the test mock a peer response, rather than to have integration tests that require additional setup and can not be run easily. It would then be possible to remove the mock and run against a live node to verify the tests are accurate.

**Comment by maraoz** [comment]
@braydonf we have https://github.com/bitpay/bitcore-p2p/blob/ff2577603f28f9bc27f56479636fdc529017fcfb/test/peer.js#L21 for that 
This tests specifically for high level workings of the protocol, interacting with a real node

**Comment by eordano** [comment]
LGTM

**Pull request merged**
