### PR TITLE
Fix #18

### LINKED ISSUE #18: bower fails when parsing bower.json
```
$ bower install bitcore-p2p
bower bitcore-p2p#*         not-cached git://github.com/bitpay/bitcore-p2p.git#*
bower bitcore-p2p#*            resolve git://github.com/bitpay/bitcore-p2p.git#*
bower bitcore-p2p#*           download https://github.com/bitpay/bitcore-p2p/archive/v0.9.1.tar.gz
bower bitcore-p2p#*            extract archive.tar.gz
bower bitcore-p2p#*         EMALFORMED Failed to read /tmp/giuscri/bower/bitcore-p2p-3028-bILKkU/bower.json

Additional error details:
Unexpected token ]
```

### PR DESCRIPTION
**Pull request by giuscri**
bower JSON parser failed to read `bower.json`

### CODE REVIEW

**Comment by maraoz** [comment]
bitcore-p2p shouldn't be in bower, as you can't connect to the bitcoin
network from the browser. I think the correct change would be to remove
bower.json

**Comment by braydonf** [comment]
`bitcore-p2p` isn't currently supported in a web browser since `Net.Socket` as used in Peer and `dns.resolve` for Pool isn't available.

**Comment by braydonf** [comment]
`bower.json` removed here: https://github.com/bitpay/bitcore-p2p/pull/20

BTW: Using WebSockets has been discussed, but it would require nodes to additionally support the service. [bitcore-explorers](https://github.com/bitpay/bitcore-explorers/) will work in browsers and communicates to the Bitcoin network via [Insight](https://github.com/bitpay/insight-api).

**Comment by giuscri** [comment]
> bitcore-explorers will work in browsers and communicates to the Bitcoin network via Insight.

nice! Thank you. I'm closing this pull request then.

**Pull request closed without merging**
